import React, { useMemo } from 'react';
import {
    LineChart,
    Line,
    XAxis,
    YAxis,
    CartesianGrid,
    Tooltip,
    ResponsiveContainer,
    Legend,
    ReferenceLine
} from 'recharts';


interface CumulativeTimelineChartProps {
    gameHistory: any[];
    currentPly: number;
}



const PLAYER_COLORS: Record<string, string> = {
    RED: '#ef4444',
    BLUE: '#3b82f6',
    GREEN: '#22c55e',
    YELLOW: '#eab308'
};

export const CumulativeTimelineChart: React.FC<CumulativeTimelineChartProps> = ({ gameHistory, currentPly }) => {
    const chartData = useMemo(() => {
        if (!gameHistory || gameHistory.length === 0) return [];

        // We want to track the cumulative 'deltaSelf' of impact score or key metrics over time.
        // For MVP, we'll track the cumulative "Frontier Size Δ" generated by each player over their turns.

        // First, filter to moves that have telemetry
        const telMoves = gameHistory.filter(h => h.telemetry);

        const cumulative: Record<string, number> = {
            RED: 0,
            BLUE: 0,
            GREEN: 0,
            YELLOW: 0
        };

        return telMoves.map((m: any) => {
            const tel = m.telemetry as any;

            // We accumulate some heuristic proxy for impact. 
            // For MVP, if we don't have impactScore yet, we'll use (deltaSelf.frontierSize + deltaSelf.mobility)
            const mvpImpact = tel.impactScore !== undefined
                ? tel.impactScore
                : ((tel.deltaSelf.frontierSize || 0) + (tel.deltaSelf.mobility || 0));

            cumulative[tel.moverId] += mvpImpact;

            return {
                ply: tel.ply,
                mover: tel.moverId,
                ...cumulative
            };
        });

    }, [gameHistory]);

    if (!chartData.length) return null;

    return (
        <div className="w-full h-full min-h-[300px] flex flex-col">
            <h3 className="text-sm font-semibold text-gray-300 mb-2 truncate">
                Cumulative Move Impact (Game Pace)
            </h3>
            <div className="flex-1">
                <ResponsiveContainer width="100%" height="100%">
                    <LineChart
                        data={chartData}
                        margin={{ top: 5, right: 30, left: 10, bottom: 5 }}
                    >
                        <CartesianGrid strokeDasharray="3 3" stroke="#4a5568" />
                        <XAxis dataKey="ply" type="number" stroke="#9ca3af" fontSize={11} domain={['dataMin', 'dataMax']} />
                        <YAxis stroke="#9ca3af" fontSize={11} width={40} />
                        <Tooltip
                            contentStyle={{ backgroundColor: '#1f2937', borderColor: '#374151', color: '#f3f4f6' }}
                            itemStyle={{ color: '#e5e7eb' }}
                            labelStyle={{ color: '#9ca3af' }}
                            labelFormatter={(label) => `Ply ${label}`}
                        />
                        <Legend wrapperStyle={{ fontSize: 12, color: '#9ca3af' }} />

                        {/* Current Move Line */}
                        {currentPly > 0 && (
                            <ReferenceLine x={currentPly} stroke="#eab308" strokeDasharray="3 3" />
                        )}

                        <Line type="monotone" dataKey="RED" stroke={PLAYER_COLORS.RED} dot={false} strokeWidth={2} />
                        <Line type="monotone" dataKey="BLUE" stroke={PLAYER_COLORS.BLUE} dot={false} strokeWidth={2} />
                        <Line type="monotone" dataKey="GREEN" stroke={PLAYER_COLORS.GREEN} dot={false} strokeWidth={2} />
                        <Line type="monotone" dataKey="YELLOW" stroke={PLAYER_COLORS.YELLOW} dot={false} strokeWidth={2} />
                    </LineChart>
                </ResponsiveContainer>
            </div>
        </div>
    );
};
